### ISSUE TITLE
show artist & title

### ISSUE THREAD

**Issue by stkw0** [stakewinner00/web_cppplayer#1]
Show the artist and title of the current song using the **/getartist/** and **/gettitle/** URIs

**Comment by bssanchez** [comment]
Fixed in commit [e23160b5c6c857b35b0c7a77f52bc6e3dbf2aa10](https://github.com/stakewinner00/web_cppplayer/commit/e23160b5c6c857b35b0c7a77f52bc6e3dbf2aa10)
