### ISSUE TITLE
Strange rectangle in dark theme

### ISSUE THREAD

**Issue by stkw0** [stakewinner00/web_cppplayer#2]
In some browsers like firefox the dark theme shows a ugly rectangle.
![image](http://oi67.tinypic.com/adf0hh.jpg)

**Comment by bssanchez** [comment]
Fixed in commit [e23160b5c6c857b35b0c7a77f52bc6e3dbf2aa10](https://github.com/stakewinner00/web_cppplayer/commit/e23160b5c6c857b35b0c7a77f52bc6e3dbf2aa10)
